# Use the official MongoDB image
FROM mongo:5.0

# Set environment variables for MongoDB
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=123456  
ENV MONGO_INITDB_DATABASE=BudgetTracker

# Expose the default MongoDB port
EXPOSE 27017
